// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHooks.Data;

namespace WebHooks.Data.Migrations
{
    [DbContext(typeof(ChangeTokenContext))]
    partial class ChangeTokenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebHooks.Data.Models.ChangeToken", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("LastChangeToken")
                        .IsRequired();

                    b.Property<string>("ListId")
                        .IsRequired();

                    b.Property<string>("WebId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ChangeTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
